scrape_configs:
  - job_name: speed-test-exporter
    scrape_interval: 15m
    static_configs:
      - targets:
          - http://speed_test_exporter:8080
  - job_name: nodes
    scrape_interval: 60s
    static_configs:
      - targets:
          - http://riko.astleymanor.net:9100
  - job_name: nodes_smartctl
    scrape_interval: 60s
    static_configs:
      - targets:
          - http://riko.astleymanor.net:9633
